<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="LogUserTest-2018_07_10_14_37_52" tests="12" time="22.576">
	<testcase classname="LogUserTest" name="test_02_correct_login_invalid_password" time="0.571"/>
	<testcase classname="LogUserTest" name="test_03_invalid_login_correct_password" time="0.543"/>
	<testcase classname="LogUserTest" name="test_04_no_login_correct_password" time="0.559"/>
	<testcase classname="LogUserTest" name="test_05_correct_login_no_password" time="0.564"/>
	<testcase classname="LogUserTest" name="test_06_admin_correct_login_and_password" time="5.514"/>
	<testcase classname="LogUserTest" name="test_07_admin_correct_login_invalid_password" time="0.514"/>
	<testcase classname="LogUserTest" name="test_08_admin_invalid_login_correct_password" time="0.486"/>
	<testcase classname="LogUserTest" name="test_09_no_admin_login_correct_password" time="0.766"/>
	<testcase classname="LogUserTest" name="test_10_admin_correct_login_no_password" time="0.561"/>
	<testcase classname="LogUserTest" name="test_11_admin_login_user_password" time="0.581"/>
	<testcase classname="LogUserTest" name="test_12_user_login_admin_password" time="0.571"/>
	<testcase classname="LogUserTest" name="test_01_correct_login_and_password" time="11.346">
		<error message="Message: 
" type="TimeoutException">
<![CDATA[Traceback (most recent call last):
  File "C:/Testy/Logowanie/LogTest.py", line 32, in test_01_correct_login_and_password
    assert self.account_page.check_login_result(self.testName)
  File "C:\Testy\Logowanie\Page\Account_page.py", line 14, in check_login_result
    self.login_page.log_result()
  File "C:\Testy\Logowanie\Page\Login_page.py", line 64, in log_result
    self.click_option_button()
  File "C:\Testy\Logowanie\Page\Login_page.py", line 51, in click_option_button
    self.option_button().click()
  File "C:\Testy\Logowanie\Page\Login_page.py", line 28, in option_button
    self.driver_commands.wait_for_element_by_css_selector(".fa-th")
  File "C:\Testy\Logowanie\Libs\Driver_commands.py", line 18, in wait_for_element_by_css_selector
    WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, element)))
  File "C:\Testy\Logowanie\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
